content = [
    "Content-Type",
    "v9.0.4 Geetest Inc.",
    "attachEvent",
    "GeeChallenge",
    "documentElement",
    "open",
    "Geetest requires a window with a document",
    "BiAz",
    "split",
    "getDate",
    "send",
    "test",
    "?",
    "navigator",
    "transition",
    "function",
    "loaded",
    "-",
    "POST",
    "onunhandledrejection",
    "application/json",
    "clearTimeout",
    "2d",
    "withCredentials",
    "Cmxg",
    "stack",
    "parse",
    "stringify",
    "setRequestHeader",
    "BackCompat",
    "undefined",
    "getElementsByTagName",
    "mozTransition",
    "protocol",
    "monitor.geetest.com/monitor/send",
    "unhandledrejection",
    "getSeconds",
    "setTimeout",
    "/monitor/send",
    "responseText",
    "object",
    "getMinutes",
    "getHours",
    "document",
    "timeout",
    "indexOf",
    "EqkY",
    "status: ",
    "//",
    "style",
    "msTransition",
    "addEventListener",
    "location",
    "status",
    "message",
    "AwTT",
    "body",
    "slice",
    "canvas",
    "filename",
    "js",
    "getFullYear",
    "webkitTransition",
    "replace",
    "onerror",
    "gt",
    "603",
    "602",
    "onreadystatechange",
    " ",
    ":",
    "exports",
    "complete",
    "compatMode",
    "Android",
    "onload",
    "",
    "readyState",
    "XMLHttpRequest",
    "0",
    "Accept",
    "text/plain;charset=utf-8",
    "3",
    "ontimeout",
    "XDomainRequest",
    "GeeGT",
    "getContext",
    "DvBr",
    "monitor.geetest.com",
    "getMonth",
    "head",
    "string",
    "JSON",
    "script",
    "error",
    "https://monitor.geetest.com/monitor/send",
    "userAgent",
    "error_code",
    "createElement",
    "post",
    "hasOwnProperty",
    ".",
    "TCit",
    "cmBe",
    "验证的js地址无法加载",
    "RoMf",
    "zh",
    "img",
    "length",
    "hk",
    "zh-cn",
    "/get.php请求报错：1.请保持网络畅通；2.检查初始化时传入的配置参数gt和challenge",
    "ip",
    "number",
    "error_109",
    "error_111",
    "SyHp",
    "XIZj",
    "NuMA",
    "IKtt",
    "err001",
    "QYPb",
    "error_107",
    "error_101",
    "error_112",
    "验证的js地址不存在",
    "stylesheet",
    "challenge",
    "FSHv",
    "pt",
    "UTF-8",
    "tw",
    "error_106",
    "Configuration Error",
    "step",
    "error_110",
    "charCodeAt",
    "网络不给力",
    "網絡不給力",
    "皮肤加载失败：1.请保持网络畅通；2.请联系极验官网客服",
    "anonymous",
    "YQqh",
    "end",
    "error_117",
    "验证图片加载失败：1.请保持网络畅通；2.请联系极验官网客服",
    "/refresh.php请求报错：1.请保持网络畅通；2.刷新次数本身有限制（10次以内），超过限制请刷新整个页面再试",
    "audio",
    "-tw",
    "error_100",
    "配置錯誤",
    "=",
    "error_105",
    "css",
    "apiserver",
    "a",
    "GDGb",
    "fromCharCode",
    "error_118",
    "PMOt",
    "error_113",
    "error_104",
    "OTXW",
    "Vwot",
    "/ajax.php请求报错：1.请保持网络畅通；2.请联系极验官网客服",
    "error_114",
    "Network failure",
    "/",
    "传给各回调的参数不是函数类型：请传入函数类型参数",
    "WVXu",
    "geetest_",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789()",
    "配置参数area有误：只接受id选择器和DOM元素，并且需保证其存在于页面中",
    "传给bindOn接口的参数有误：只接受id选择器和DOM元素，并且需保证其存在于页面中",
    "KsjU",
    "callback",
    "res",
    "传给appendTo接口的参数有误：只接受id选择器和DOM元素，并且需保证其存在于页面中",
    "HZuJ",
    "error_116",
    "push",
    "配置错误",
    "msg",
    "offline",
    "error_102",
    "bGsN",
    "link",
    "MuoB",
    "err002",
    "charAt",
    "&",
    "error_103",
    "error_108",
    "配置参数gt有误：请检查初始化时传入的配置参数gt（对应申请时的ID）",
    "toLowerCase",
    "JTXX",
    "-cn",
    "api_server",
    "error_115",
    "en",
    "/reset.php请求报错：1.请保持网络畅通；2.请联系极验官网客服",
    "Microsoft Internet Explorer",
    "用户回调函数执行异常",
    "604",
    "substr",
    "i",
    "call",
    "fromString",
    "clamp",
    "type",
    "ele",
    "语音文件加载失败：1.请保持网络畅通；2.请联系极验官网客服",
    "DV",
    "gdtE",
    "copyTo",
    "am",
    "maJn",
    "oMtw",
    "next",
    "iOdN",
    "initGeetest里面的gt或者challenge参数缺少: 请检查初始化参数",
    "Start",
    "abs",
    "crypto",
    "0123456789abcdefghijklmnopqrstuvwxyz",
    "detail",
    "mousemove",
    "toRadix",
    "pow",
    "./usercallback/",
    "isEmpty",
    "sLlQ",
    "jZzQ",
    "queue is empty",
    "DB",
    ": ",
    "getRandomValues",
    "fromNumber",
    "appName",
    "init",
    "random",
    "F1",
    "lang",
    "传给bindForm接口的参数有误：只接受id选择器和DOM元素，并且需保证其存在于页面中",
    "fromInt",
    "min",
    "PENDING",
    "tVxj",
    "removeEventListener",
    "subTo",
    "y",
    "fromRadix",
    "ZERO",
    "onmousemove",
    "S",
    "code",
    "kJjd",
    "floor",
    "nextBytes",
    "DM",
    "jscrambler",
    "unknown",
    "lcDF",
    "FV",
    "detachEvent",
    "End",
    "UserCallBackError",
    "toString",
    "debug",
    "max",
    "j",
    "all",
    "Start controlFlowFlattening",
    "then",
    "s",
    "hCQK",
    "uaiN",
    "Netscape",
    "user_error",
    "RESOLVED",
    "vvif",
    "qUDV",
    "t",
    "each",
    "paFC",
    "rdIy",
    "enqueue",
    "无此类错误类型",
    "clear",
    "\n",
    "REJECTED",
    "negate",
    "ngVJ",
    "prototype",
    "x",
    "race",
    "A",
    "F2",
    "服务端forbidden： 请联系极验官网客服",
    "GeetestError",
    "dequeue",
    "isArray",
    "sc",
    "JGDr",
    "si",
    "q",
    "join",
    "ek",
    "data",
    "fileName",
    "EwSb",
    "encrypt",
    "cp",
    "mph",
    "wd",
    "convert",
    "um",
    "Invalid RSA public key",
    "forEach",
    "00C1E3934D1614465B33053E7F48EE4EC87B14B95EF88947713D25EECBFF7E74C7977D02DC1D9451F79DD5D1C10C29ACB6A9B4D6FB7D0A0279B6719E1772565F09AF627715919221AEF91899CAE08C0D686D748B20A3603BE2318CA6BC2B59706592A9219D0BF05C9F65023A21D2330807252AE0066D59CEEFA5F2748EA80BAB81",
    "fn",
    "m",
    "[object Array]",
    "UAyO",
    "get",
    "dmp1",
    "doPublic",
    "callP",
    "e",
    "compareTo",
    "mulTo",
    "coeff",
    "wENh",
    "lShiftTo",
    "kCKx",
    "boolean",
    "fkyA",
    "splice",
    "concat",
    "hantom",
    "revert",
    "nt",
    "HNWI",
    "ph",
    "dlShiftTo",
    "isEven",
    "_nig",
    "divRemTo",
    "d",
    "noConflict",
    "rShiftTo",
    "getTime",
    "CZzt",
    "mt2",
    "getPrototypeOf",
    "re",
    "mpl",
    "valueOf",
    "modPowInt",
    "column",
    "_p",
    "ZLmcfl_",
    "djflasu",
    "invDigit",
    "constructor",
    "$cdc_as",
    "description",
    "user_callback",
    "lYIw",
    "ONE",
    "slide",
    "value",
    "Geetest",
    "squareTo",
    "dmq1",
    "mp",
    "exp",
    "multiplyTo",
    "n",
    "htma",
    "xpjf",
    "sqrTo",
    "bitLength",
    "shell",
    "substring",
    "10001",
    "Number",
    "Gk_g",
    "DpgD",
    "drShiftTo",
    "getOwnPropertyDescriptor",
    "sourceURL",
    "reduce",
    "line",
    "setPublic",
    "topfhvc",
    "_",
    "p",
    "mod",
    "webdriver",
    "Message too long for RSA",
    "visible",
    "insertBefore",
    "outerHTML",
    "ngcz",
    "getComputedStyle",
    "resize",
    "MSPointerUp",
    "id",
    "$_sTyyle",
    "BUCv",
    "sandbox",
    "MSPointerDown",
    "removeChild",
    "touchend",
    "keyup",
    "blur",
    "jMkL",
    "pageYOffset",
    "currentStyle",
    "offsetTop",
    "beforeunload",
    "getBoundingClientRect",
    "ELEMENT_NODE",
    "tagName",
    "hidden",
    "focus",
    "touchmove",
    "MRcc",
    "keydown",
    "MSPointerMove",
    "scrollLeft",
    "right",
    "qLQF",
    "mouseup",
    "jQuery",
    "setAttribute",
    "left",
    "play",
    "pointermove",
    "getAttribute",
    "href",
    "touchcancel",
    "click",
    "pointerup",
    "NSlK",
    "offsetLeft",
    "parentNode",
    "createTextNode",
    "mousedown",
    "childNodes",
    "pointerdown",
    "className",
    "QoAd",
    "offsetParent",
    "styleSheet",
    "OvKK",
    "ended",
    "scroll",
    "round",
    "origin_",
    "cZHm",
    "unload",
    "oVMi",
    "input",
    "children",
    "pause",
    "scrollTop",
    "clientTop",
    "touchstart",
    "#",
    "focusin",
    "pageXOffset",
    "div",
    "querySelector",
    "clientLeft",
    "mouseenter",
    "pageshow",
    "ikyM",
    "on",
    "width",
    "cloneNode",
    "removeAttribute",
    "$",
    "SaAZ",
    "cssText",
    "appendChild",
    "block",
    "mouseleave",
    "bottom",
    "none",
    "innerHTML",
    "getPropertyValue",
    "WwRv",
    "getElementById",
    "currentTime",
    "height",
    "XLAu",
    "toLocaleLowerCase",
    "top",
    "overflow",
    "illegal catch attempt",
    "Generator",
    "rval",
    "]",
    "getUTCMinutes",
    "\"",
    "[\n",
    "arg",
    "\\\"",
    "[object Generator]",
    "\\r",
    "assign",
    "clientX",
    "IDjG",
    "Argument must be an object, or null",
    "delegate",
    "toStringTag",
    "toFixed",
    "Generator is already running",
    "finallyLoc",
    "this is null or not defined",
    "tryLoc",
    "reset",
    "0000",
    "{",
    "host",
    "getUTCFullYear",
    "[]",
    "keys",
    "normal",
    "null",
    "continue",
    "Aqsv",
    "NwKz",
    "{\n",
    "JSON.stringify",
    "root",
    "apply",
    "reverse",
    "{}",
    "}",
    "iterator",
    "suspendedYield",
    "clientY",
    "/iframe.1.0.5.html?w=",
    " is not a function",
    ",",
    "toJSON",
    "cancelable",
    "getUTCSeconds",
    "@@iterator",
    "\\b",
    "\\f",
    "executing",
    "\\t",
    "GeneratorFunction",
    "T",
    "index",
    "catchLoc",
    "getUTCHours",
    "done",
    "completed",
    "getUTCMonth",
    "try statement without catch or finally",
    "Z",
    "suspendedStart",
    "MMGy",
    "displayName",
    "pop",
    "abrupt",
    "plKS",
    "return",
    "preventDefault",
    "w",
    "px",
    "returnValue",
    "prev",
    "\\\\",
    "setPrototypeOf",
    "dispatchException",
    "mark",
    "nodeType",
    "stopPropagation",
    "[",
    "create",
    "throw",
    "completion",
    "break",
    "afterLoc",
    "\\n",
    "\\u",
    "@@toStringTag",
    "lastIndex",
    "getUTCDate",
    "Cannot convert undefined or null to object",
    "changedTouches",
    ",\n",
    "tryEntries",
    "sent",
    "method",
    "/static/js/worker.",
    "progress",
    "stop",
    "gt_w_stop_",
    "requestStart",
    "beforeStart",
    "getExtension",
    "selenium",
    "redirectStart",
    "loadEventEnd",
    "config",
    "domLoading",
    "timing",
    "mouseEvent",
    "OuWx",
    "border",
    "loadEventStart",
    "renderer",
    "gt_w_error_",
    "VENDOR",
    "domContentLoadedEventEnd",
    "supportWorker",
    "&t=",
    "vip_key",
    "callPhantom",
    "domContentLoadedEventStart",
    "SwiftShader",
    "deviceorientation",
    "iframeurl",
    "start",
    "bigCombination",
    "loadCb",
    "navigationStart",
    "*",
    "performance",
    "vendor",
    "phantom",
    "c",
    "k",
    "puppet",
    "__nightmare",
    "WEBGL_debug_renderer_info",
    "gamma",
    "static.geetest.com",
    "getParameter",
    "alpha",
    "readyCb",
    "touchEvent",
    "postMessage",
    "secureConnectionStart",
    "redirectEnd",
    "Krvi",
    "domComplete",
    "domainLookupStart",
    "&mid=",
    "Rkvd",
    "UNMASKED_VENDOR_WEBGL",
    "errorCb",
    "result",
    "debugConfig",
    "connectStart",
    ".js",
    "posX",
    "/gt-dist/html",
    "experimental-webgl",
    "unloadEventStart",
    "PDuN",
    "worker_version",
    "worker_path",
    "Sbxv",
    "gt_w_start_",
    "connectEnd",
    "gt_w_ready_",
    "unloadEventEnd",
    "/static/html",
    "src",
    "responseStart",
    "contentWindow",
    "sort",
    "responseEnd",
    "vip_answer",
    "fetchStart",
    "domInteractive",
    "domainLookupEnd",
    "beta",
    "iframe",
    "ceil",
    "position",
    "absolute",
    "gt_w_progress_",
    "gt_w_done_",
    "RENDERER",
    "UNMASKED_RENDERER_WEBGL",
    "PlLE",
    "vip_content",
    "/static",
    "_phantom",
    "powclient",
    "nightmare",
    "static_servers",
    "P",
    "canvas2DFP",
    "BUTTON",
    "IVtC",
    "TqDL",
    "doNotTrack",
    "CANVAS",
    "textLength",
    "IFRAME",
    "browserLanguages",
    "screenWidth",
    "rXCb",
    "screenAvailTop",
    "screenHeight",
    "screenAvailWidth",
    "STYLE",
    "eHEC",
    "screenAvailHeight",
    "nPIt",
    "up",
    "lKUL",
    "mouse",
    "touch",
    "pf_L",
    "log",
    "fOjW",
    "plugins",
    "busi",
    "LI",
    "outerWidth",
    "documentMode",
    "SPAN",
    "BASE",
    "YYFv",
    "canvas3DFP",
    "ZMY_",
    "IMG",
    "SCRIPT",
    "innerHeight",
    "ARTICLE",
    "dRbs",
    "JtaI",
    "ceHa",
    "OL",
    "lastTime",
    "down",
    "CODE",
    "CPUClass",
    "posY",
    "TABLE",
    "UL",
    "outerHeight",
    "INPUT",
    "btMx",
    "localStorageEnabled",
    "LINK",
    "AUDIO",
    "ycIg",
    "hqHl",
    "OBJECT",
    "Wwfb",
    "SECTION",
    "LABEL",
    "parseInt",
    "devicePixelRatio",
    "()*,-./0123456789:?@ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz~",
    "screenAvailLeft",
    "colorDepth",
    "gcNs",
    "TEXTAREA",
    "timezone",
    "HTMLLength",
    "platform",
    "1",
    "indexedDBEnabled",
    "netEnabled",
    "XCxj",
    "screenTop",
    "pointer",
    "browserLanguage",
    "screenLeft",
    "VhN_",
    "ohaK",
    "PICTURE",
    "UCJd",
    "SOURCE",
    "innerWidth",
    "ZLnc",
    "VIDEO",
    "MSPointer",
    "cookieEnabled",
    "systemLanguage",
    "ASIDE",
    "SELECT",
    "NAV",
    "avNh",
    "move",
    "DIV",
    "PRE",
    "sessionStorageEnabled",
    "rgb(255,255,0)",
    "nodeName",
    "beginPath",
    "fillText",
    "rect",
    "STATIC_DRAW",
    "useProgram",
    "Cwm fjordbank glyphs vext quiz, 😃",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "rgb(0,255,255)",
    "canvas winding:",
    "FRAGMENT_SHADER",
    "#069",
    ", ",
    "bufferData",
    "MAX_TEXTURE_MAX_ANISOTROPY_EXT",
    "toDataURL",
    "availTop",
    "soBk",
    "jsFonts",
    "cpuClass",
    "userLanguage",
    "bindBuffer",
    "MOZ_EXT_texture_filter_anisotropic",
    "getAttribLocation",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "display",
    "globalCompositeOperation",
    "performanceTiming",
    "11pt Arial",
    "isPointInPath",
    "textContent",
    "rgb(255,0,255)",
    "linkProgram",
    "vertexPosAttrib",
    "language",
    "maxTouchPoints",
    "DEPTH_TEST",
    "offsetUniform",
    "PI",
    "pShT",
    "ARRAY_BUFFER",
    "localStorage",
    "WEBKIT_EXT_texture_filter_anisotropic",
    "clearColor",
    "textBaseline",
    "multiply",
    "createShader",
    "getTimezoneOffset",
    "onLine",
    "fillStyle",
    "compileShader",
    "availHeight",
    "font",
    "languages",
    "sessionStorage",
    "uniformOffset",
    "numItems",
    "rgba(102, 204, 0, 0.7)",
    "hardwareConcurrency",
    "attrVertex",
    "indexedDB",
    "18pt Arial",
    "timestamp",
    "alphabetic",
    "arc",
    "VERTEX_SHADER",
    "createBuffer",
    "availLeft",
    "innerText",
    "inline",
    "screen",
    "fill",
    "EXT_texture_filter_anisotropic",
    "enableVertexAttribArray",
    "availWidth",
    "getUniformLocation",
    "COLOR_BUFFER_BIT",
    "itemSize",
    "mediaDevices",
    "depthFunc",
    "~",
    "flashEnabled",
    "attachShader",
    "webgl",
    "no",
    "#f60",
    "yes",
    "shaderSource",
    "internalip",
    "LEQUAL",
    "canvas fp:",
    "createProgram",
    "evenodd",
    "enable",
    "fillRect",
    "closePath",
    "javaEnabled",
    "toUpperCase",
    "DEPTH_BUFFER_BIT",
    "webgl max anisotropy:",
    "MAX_VERTEX_ATTRIBS",
    "webgl vertex shader high int precision rangeMax:",
    "HIGH_FLOAT",
    "getSupportedExtensions",
    "HIGH_INT",
    "webgl max combined texture image units:",
    "webgl blue bits:",
    "webgl max render buffer size:",
    "VERSION",
    "getContextAttributes",
    "webgl fragment shader low float precision rangeMax:",
    "webgl fragment shader high float precision rangeMax:",
    "webgl fragment shader low float precision rangeMin:",
    "DEPTH_BITS",
    "webgl fragment shader high int precision rangeMin:",
    "MAX_CUBE_MAP_TEXTURE_SIZE",
    "webgl max fragment uniform vectors:",
    "RED_BITS",
    "MAX_VARYING_VECTORS",
    "webgl vertex shader medium float precision:",
    "MAX_FRAGMENT_UNIFORM_VECTORS",
    "webgl max vertex attribs:",
    "vertexAttribPointer",
    "ALIASED_LINE_WIDTH_RANGE",
    "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
    "webgl stencil bits:",
    "STENCIL_BITS",
    "webgl vertex shader high int precision:",
    "webgl vertex shader medium int precision rangeMin:",
    "MAX_TEXTURE_SIZE",
    "webgl max cube map texture size:",
    "webgl aliased point size range:",
    "webgl max texture image units:",
    "webgl vertex shader high float precision rangeMin:",
    "webgl fragment shader high int precision:",
    "webgl max vertex uniform vectors:",
    "webgl fragment shader medium float precision rangeMin:",
    "webgl vertex shader medium float precision rangeMin:",
    "webgl shading language version:",
    "webgl red bits:",
    "webgl vendor:",
    "LOW_INT",
    "webgl fragment shader medium int precision rangeMax:",
    "MEDIUM_INT",
    "webgl aliased line width range:",
    "rangeMin",
    "webgl renderer:",
    "webgl vertex shader low float precision rangeMax:",
    "webgl max viewport dims:",
    "webgl vertex shader high int precision rangeMin:",
    "GREEN_BITS",
    "FLOAT",
    "webgl vertex shader high float precision:",
    "webgl fragment shader medium float precision:",
    "MAX_RENDERBUFFER_SIZE",
    "getShaderPrecisionFormat",
    "webgl fragment shader high int precision rangeMax:",
    "webgl vertex shader low float precision:",
    "webgl vertex shader high float precision rangeMax:",
    "webgl max varying vectors:",
    "uniform2f",
    "precision",
    "webgl vertex shader low int precision:",
    "webgl antialiasing:",
    "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
    "webgl fragment shader medium float precision rangeMax:",
    "MEDIUM_FLOAT",
    "webgl alpha bits:",
    "webgl fragment shader medium int precision:",
    "MAX_TEXTURE_IMAGE_UNITS",
    "webgl version:",
    "SHADING_LANGUAGE_VERSION",
    "webgl vertex shader medium float precision rangeMax:",
    "vertexPosArray",
    "ALIASED_POINT_SIZE_RANGE",
    "webgl vertex shader low int precision rangeMin:",
    "webgl fragment shader high float precision:",
    "MAX_VERTEX_UNIFORM_VECTORS",
    "webgl fragment shader high float precision rangeMin:",
    "webgl max vertex texture image units:",
    "webgl fragment shader low float precision:",
    "drawArrays",
    "BLUE_BITS",
    "webgl depth bits:",
    "extensions:",
    "webgl vertex shader medium int precision:",
    ";",
    "TRIANGLE_STRIP",
    "MAX_VIEWPORT_DIMS",
    "webgl vertex shader low int precision rangeMax:",
    "webgl vertex shader medium int precision rangeMax:",
    "antialias",
    "rangeMax",
    "ALPHA_BITS",
    "webgl vertex shader low float precision rangeMin:",
    "LOW_FLOAT",
    "webgl fragment shader medium int precision rangeMin:",
    "webgl green bits:",
    "webgl max texture size:",
    "swfobject",
    "Segoe UI",
    "Segoe UI Symbol",
    "Bitstream Vera Sans Mono",
    "Times",
    "Trebuchet MS",
    "Comic Sans",
    "mmmmmmmmmmlli",
    "Century Gothic",
    "MS Outlook",
    "Arial Black",
    "Wingdings 3",
    "Helvetica Neue",
    "Lucida Console",
    "Cambria Math",
    "Segoe Script",
    "MS Serif",
    "Century",
    "Microsoft Sans Serif",
    "webgl fragment shader low int precision:",
    "MS Sans Serif",
    "Georgia",
    "wvOb",
    "Aria1",
    "MS Reference Sans Serif",
    "Segoe Print",
    "Book Antiqua",
    "Palatino Linotype",
    "offsetHeight",
    "webgl fragment shader low int precision rangeMin:",
    "fontSize",
    "webgl fragment shader low int precision rangeMax:",
    "magic data",
    "fontFamily",
    "Helvetica",
    "yiFS",
    "xdro",
    "offsetWidth",
    "Lucida Sans Unicode",
    "Arial Rounded MT Bold",
    "Times New Roman PS",
    "LUCIDA GRANDE",
    "!!",
    "target",
    "Arial Unicode MS",
    "Wingdings",
    "hasFlashPlayerVersion",
    "Lucida Bright",
    "monospace",
    "Andale Mono",
    "Garamond",
    "MS Gothic",
    "MS PGothic",
    "Courier New",
    "'",
    "uKEh",
    "Impact",
    "msMaxTouchPoints",
    "jkYm",
    "Lucida Handwriting",
    "Wingdings 2",
    "Lucida Fax",
    "Monotype Corsiva",
    "MYRIAD PRO",
    "Lucida Sans Typewriter",
    "Verdana",
    "',",
    "vUrA",
    "Bookman Old Style",
    "Geneva",
    "Times New Roman",
    "Calibri",
    "Palatino",
    "span",
    "9.0.0",
    "|",
    "tTqE",
    "Comic Sans MS",
    "srcElement",
    "Cambria",
    "-9999px",
    "Courier",
    "Lucida Calligraphy",
    "Arial",
    "Arial Hebrew",
    "Arial MT",
    "serif",
    "Century Schoolbook",
    "mnJq",
    "MYRIAD",
    "sans-serif",
    "Tahoma",
    "Lucida Sans",
    "quyQ",
    "Monaco",
    "72px",
    "Segoe UI Semibold",
    "Consolas",
    "Arial Narrow",
    "Segoe UI Light",
    "not_compatible",
    "ready",
    "Click to pass",
    "blockSize",
    "驗證成功",
    "网络故障",
    "Click to retry",
    "IWOL",
    "点击按钮进行验证",
    "DHUf",
    "detect",
    "Please finish it",
    "An error occured. Please refresh and try again!",
    "由極驗提供技術支持",
    "mixIn",
    "CqNl",
    "请完成验证",
    "Base",
    "Loading",
    "Utf8",
    "close",
    "智能检测中",
    "zh-hk",
    "智能驗證檢測中",
    "$super",
    "智能檢測中",
    "radar_click_hide",
    "radar_success",
    "radar_error",
    "radar_click",
    "popup",
    "通过验证",
    "HlnI",
    "Bbdd",
    "compute_1",
    "float",
    "lib",
    "Succeeded",
    "mozBoxSizing",
    "頁面出現錯誤啦！要繼續操作，請刷新此頁面。",
    "i18n_labels",
    "Going to Geetest（verification service provider）？",
    "sigBytes",
    "Cancel",
    "請點擊重試",
    "radar_click_ready",
    "LDZE",
    "请点击重试",
    "Network Error",
    "前往",
    "网络超时",
    "點擊按鈕進行驗證",
    "webkitBoxSizing",
    "验证成功",
    "cfg",
    "bind",
    "Network timeout",
    "custom",
    "JsLk",
    "success",
    "algo",
    "網絡故障",
    "請點擊此處重試",
    "请点击此处重试",
    "click_error",
    "wait_compute",
    "compute_2",
    "正在加載驗證",
    "enc",
    "页面出现错误啦！要继续操作，请刷新此页面。",
    "BufferedBlockAlgorithm",
    "正在加载验证",
    "words",
    "back",
    "grar",
    "由极验提供技术支持",
    "boxSizing",
    "Detecting",
    "EZCb",
    "GSeu",
    "請完成驗證",
    "FQgp",
    "Latin1",
    "ARSH",
    "是否前往驗證服務Geetest官網？",
    "Provided by Geetest",
    "extend",
    "取消",
    "是否前往验证服务Geetest官网？",
    "start_compute",
    "通過驗證",
    "智能验证检测中",
    "start_detect",
    "el",
    "Success",
    ".geetest_holder.geetest_wind{width:260px;min-width:260px;height:44px}.geetest_holder.geetest_wind .geetest_radar_btn,.geetest_holder.geetest_wind .geetest_success_btn{border:1px solid #ccc;border-radius:2px;min-width:160px}.geetest_holder.geetest_wind .geetest_success_btn{cursor:default;border-color:#26C267}.geetest_holder.geetest_wind .geetest_radar_btn{left:0}.geetest_holder.geetest_wind .geetest_offline{border:4px solid #FE984C;_height:6px;_width:6px;border-bottom-color:transparent;border-left-color:transparent;_border-width:0}.geetest_holder.geetest_wind .geetest_success_btn{*right:-2px;background:#EEFFF5}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box{top:9px;left:7px;width:24px;height:24px}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box .geetest_success_show{width:24px;height:24px}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box .geetest_success_show .geetest_success_pie{border:2px solid #80D6AC;border-left:none;border-radius:0 100% 100% 0 / 0 50% 50% 0}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box .geetest_success_show .geetest_success_filter{border:2px solid #80D6AC;border-right:none;border-radius:100% 0 0 100% / 50% 0 0 50%}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box .geetest_success_correct{right:-4px;top:-4px;width:28px;height:28px}.geetest_holder.geetest_wind .geetest_success_btn .geetest_success_box .geetest_success_correct .geetest_success_icon{top:6px;right:6px;width:18px;height:18px;-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}.geetest_holder.geetest_wind .geetest_radar{margin:6px;width:30px;height:30px}.geetest_holder.geetest_wind .geetest_radar .geetest_ring{box-shadow:inset 0 0 0 1px #3873ff}.geetest_holder.geetest_wind .geetest_radar .geetest_cross .geetest_v{height:4px}.geetest_holder.geetest_wind .geetest_radar .geetest_cross .geetest_h{width:4px}.geetest_holder.geetest_wind .geetest_radar .geetest_scan .geetest_h{box-shadow:0 0 1px #aedbfb}.geetest_holder.geetest_wind .geetest_radar_tip,.geetest_holder.geetest_wind .geetest_success_radar_tip{padding:0 46px 0 46px;height:42px;line-height:42px;font-size:14px}.geetest_holder.geetest_wind .geetest_radar_tip .geetest_reset_tip_content,.geetest_holder.geetest_wind .geetest_success_radar_tip .geetest_reset_tip_content{margin-left:5px}.geetest_holder.geetest_wind .geetest_radar_tip.geetest_multi_line{line-height:20px}.geetest_holder.geetest_wind .geetest_radar_tip.geetest_reversal{padding:0 46px 0 46px}.geetest_holder.geetest_wind .geetest_success_radar_tip.geetest_reversal_success{padding:0 46px 0 46px}.geetest_holder.geetest_wind .geetest_success_radar_tip_timeinfo{margin-left:10px;font-size:12px}.geetest_holder.geetest_wind .geetest_logo,.geetest_holder.geetest_wind .geetest_success_logo{right:12px;width:20px;height:20px;top:11px}.geetest_holder.geetest_wind .geetest_wait{margin:17px 12px}.geetest_holder.geetest_wind .geetest_wait .geetest_wait_dot{width:5px;height:5px;margin:2px}.geetest_holder.geetest_wind.geetest_compute_1 .geetest_radar .geetest_ring{box-shadow:inset 0 0 0 2px #3873ff}.geetest_holder.geetest_wind.geetest_compute_2 .geetest_radar .geetest_ring{box-shadow:inset 0 0 0 2px #3873ff}@keyframes geetest_success_correct{0%{-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}30%{-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}90%{-moz-transform:translate(3px, -2px);-ms-transform:translate(3px, -2px);-webkit-transform:translate(3px, -2px);transform:translate(3px, -2px)}100%{-moz-transform:translate(1px, 0);-ms-transform:translate(1px, 0);-webkit-transform:translate(1px, 0);transform:translate(1px, 0)}}@-webkit-keyframes geetest_success_correct{0%{-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}30%{-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}90%{-moz-transform:translate(3px, -2px);-ms-transform:translate(3px, -2px);-webkit-transform:translate(3px, -2px);transform:translate(3px, -2px)}100%{-moz-transform:translate(1px, 0);-ms-transform:translate(1px, 0);-webkit-transform:translate(1px, 0);transform:translate(1px, 0)}}.geetest_holder.geetest_wind.geetest_radar_error .geetest_radar_tip .geetest_radar_error_code{font-size:12px;right:1px}.geetest_holder.geetest_wind.geetest_ie .geetest_ie_radar{top:16px;left:16px;width:12px;height:12px}.geetest_holder.geetest_wind.geetest_ie.geetest_not_compatible .geetest_ie_radar,.geetest_holder.geetest_wind.geetest_ie.geetest_radar_success .geetest_ie_radar,.geetest_holder.geetest_wind.geetest_ie.geetest_radar_error .geetest_ie_radar{top:14px;left:14px;width:16px;height:16px}@keyframes geetest_shake{25%{margin-left:-6px}75%{margin-left:6px}100%{margin-left:0}}@-webkit-keyframes geetest_shake{25%{margin-left:-6px}75%{margin-left:6px}100%{margin-left:0}}.geetest_wind.geetest_fullpage_click .geetest_fullpage_click_box{border-radius:2px}.geetest_wind.geetest_fullpage_click.geetest_float .geetest_fullpage_pointer{margin-left:-15px}.geetest_wind.geetest_fullpage_click.geetest_float .geetest_fullpage_pointer .geetest_fullpage_pointer_out{border:8px solid #cccccc;border-color:transparent #cccccc transparent transparent}.geetest_wind.geetest_fullpage_click.geetest_float .geetest_fullpage_pointer .geetest_fullpage_pointer_in{border:7px solid #fff;margin:1px 0 1px 2px;border-color:transparent #fff transparent transparent}.geetest_wind.geetest_fullpage_click.geetest_float .geetest_fullpage_click_box{box-shadow:0 0 10px #cccccc;border:1px solid #cccccc;margin:-10px 5px 5px 0}.geetest_wind.geetest_fullpage_click.geetest_float.geetest_slide .geetest_fullpage_click_box{max-width:320px}.geetest_wind.geetest_fullpage_click.geetest_popup .geetest_fullpage_click_wrap{max-width:356px;min-width:260px;width:80%;width:356px 9;margin-left:-178px 9;margin-top:-245px 9}.geetest_wind.geetest_goto .geetest_goto_wrap{max-width:300px;border-radius:2px;font-size:16px}.geetest_wind.geetest_goto .geetest_goto_wrap .geetest_goto_content{border-bottom:1px solid #e8e8e8}.geetest_wind.geetest_goto .geetest_goto_wrap .geetest_goto_content .geetest_goto_content_tip{line-height:16px}.geetest_wind.geetest_goto .geetest_goto_wrap a.geetest_goto_confirm,.geetest_wind.geetest_goto .geetest_goto_wrap .geetest_goto_cancel{height:46px;line-height:46px}.geetest_wind.geetest_goto .geetest_goto_wrap .geetest_goto_cancel{border-right:1px solid #e8e8e8}.geetest_wind.geetest_panel .geetest_panel_ghost{_width:2000px;_height:1000px}.geetest_wind.geetest_panel .geetest_panel_box{width:220px;height:150px;margin-left:-110px;margin-top:-70px;box-shadow:0 1px 8px rgba(128,128,128,0.3);border:1px solid #d1d1d1;border-radius:2px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_offline{border:4px solid #FE984C;border-bottom-color:transparent;border-left-color:transparent;_height:6px;_width:6px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error{height:113px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_temp,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading .geetest_panel_loading_title,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading .geetest_panel_loading_content,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_title,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_title,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_content{font-size:14px;height:14px;line-height:14px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading{padding:29px 0 0 0;height:84px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading .geetest_panel_loading_icon{width:32px;height:32px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading .geetest_panel_loading_title{margin:10px 0 0 0}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_loading .geetest_panel_loading_content{margin:8px 0 0 0}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success{padding:40px 0 0 0;height:73px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box{width:24px;height:24px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box .geetest_panel_success_show{width:24px;height:24px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box .geetest_panel_success_show .geetest_panel_success_pie{border:2px solid #80D6AC;border-left:none;border-radius:0 100% 100% 0 / 0 50% 50% 0}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box .geetest_panel_success_show .geetest_panel_success_filter{border:2px solid #80D6AC;border-right:none;border-radius:100% 0 0 100% / 50% 0 0 50%}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box .geetest_panel_success_correct{right:-4px;top:-4px;width:28px;height:28px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_box .geetest_panel_success_correct .geetest_panel_success_icon{top:6px;right:6px;width:18px;height:18px;-moz-transform:translate(-28px, 28px);-ms-transform:translate(-28px, 28px);-webkit-transform:translate(-28px, 28px);transform:translate(-28px, 28px)}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_success .geetest_panel_success_title{margin:10px 0 0 0}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error{padding:18px 0 0 0;height:90px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_icon{width:18px;height:18px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_title{margin:10px 0 0 0}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_content{margin:14px auto 0;font-size:12px;width:202px;height:32px;border-radius:3px;line-height:32px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_code{right:9px;top:9px;width:20px;height:17px;border-radius:2px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_error .geetest_panel_error_code .geetest_panel_error_code_text{font-size:12px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_footer{border-top:0.5px solid #efefef;padding:12px 0 8px;height:11px;margin-top:7px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_footer .geetest_panel_footer_logo,.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_footer .geetest_panel_footer_copyright{line-height:11px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_footer .geetest_panel_footer_logo{margin-right:-6px;width:11px;height:11px;margin-left:10px}.geetest_wind.geetest_panel .geetest_panel_box .geetest_panel_footer .geetest_panel_footer_copyright{font-size:10px}.geetest_wind.geetest_panel .geetest_panel_box.geetest_panelshowslide{width:278px;height:285px;margin-left:-139px;margin-top:-143px}.geetest_wind.geetest_panel .geetest_panel_box.geetest_panelshowbeeline{width:300px;height:150px;margin-left:-139px;margin-top:-143px}.geetest_wind.geetest_panel .geetest_panel_box.geetest_panelshowclick{width:320px;height:410px;margin-left:-160px;margin-top:-205px}.geetest_wind.geetest_panel .geetest_panel_box.geetest_ie6panelshowclick{width:348px;height:445px;marginLeft:-174px;marginTop:-223px}.geetest_wind.geetest_panel .geetest_panel_box.geetest_no_logo .geetest_panel_error{padding:34px 0 0}.geetest_wind.geetest_panel .geetest_panel_box.geetest_no_logo .geetest_panel_loading{padding:47px 0 0 0}.geetest_wind.geetest_panel .geetest_panel_box.geetest_no_logo .geetest_panel_error_content{margin:33px auto 0}",
    "Cipher",
    "網絡超時",
    "WordArray",
    "Yes",
    "pow_starting",
    "product",
    "Lxhe",
    "OsjB",
    "iZpQ",
    "sAeJ",
    "flush",
    "Ryvw",
    "nvNx",
    "Encryptor",
    "format",
    "aBxe",
    "fbIX",
    "padding",
    "SerializableCipher",
    "/get.php",
    "processBlock",
    "kbJx",
    "NXUA",
    "geetestPlugin",
    "geetestEvent",
    "ciphertext",
    "finalize",
    "iv",
    "AQzs",
    "wutH",
    "XFSM",
    "ww",
    "Hq_C",
    "dispatchEvent",
    "ADmW",
    "PWGm",
    "emls",
    "oVPT",
    "UweF",
    "pow_progress",
    "pad",
    "SYEP",
    "ljKL",
    "staticservers",
    "wKOo",
    "0000000000000000",
    "EhYn",
    "https://",
    "cMAQ",
    "web_mobile",
    "NtnQ",
    "uOFI",
    "encryptBlock",
    "tyhk",
    "aKqv",
    "vuFw",
    "web",
    "https",
    "config_lack",
    "CipherParams",
    "CBC",
    "qvlc",
    "MfMi",
    "geetest_data_share_plugin",
    "mESN",
    "GAny",
    "LVcI",
    "BlockCipherMode",
    "xOhH",
    "huiQ",
    "Zxsa",
    "VcwU",
    "encrypt1",
    "FRcZ",
    "createEncryptor",
    "TpUy",
    "KpyI",
    "dxPi",
    "rfaZ",
    "IBGZ",
    "BlockCipher",
    "pCSh",
    "error_21",
    "emQS",
    "powworkerdone",
    "rem",
    "QIHs",
    "Bbbp",
    "AES",
    "MakU",
    "CGab",
    "cc",
    "WdmG",
    "jWxl",
    "pure",
    "remUnit",
    "bKDU",
    "mode",
    "fFtZ0VaY4Gg",
    "YjLx",
    "gFZk",
    "yMML",
    "Pkcs7",
    "url_get",
    ".radar_error_code",
    "QQee",
    "ur",
    "\":",
    "url_skin",
    "aeskey",
    "VQFu",
    ".fallback",
    "hi",
    "me",
    "te",
    ".radar_tip_content",
    "gBLn",
    "bbOy",
    "\"captcha_token\":\"",
    "dkTe",
    "fEkexGxOwUyY",
    "Ryzo",
    "TIQp",
    "ep",
    "PjCn",
    ".holder.ie.",
    "ZLbw",
    "|jordan",
    "exec",
    "ven",
    ".holder.",
    "wind",
    "forbidden",
    "fAST",
    "lp",
    "/reset.php",
    "theme",
    "vKuE",
    "YBoS",
    "de",
    "client_type",
    "ar",
    "Dvwz",
    "score",
    "qwe",
    "1.5.8",
    "tVyd",
    "dn-staticdown.qbox.me",
    "fp",
    "iw",
    "hkwW",
    "XaPp",
    "eJPB",
    "hh",
    "YbaG",
    "uqVA",
    "rp",
    "SAkO",
    "ren",
    ".panel_error_title",
    "tm",
    "9.0.4",
    "DREY",
    "h",
    "pjFV",
    "validate",
    "https://www.geetest.com/first_page",
    "fullpage",
    ".success_radar_tip_content",
    "jeoK",
    "OLqi",
    "url_ajax",
    "kxGZ",
    "rkWg",
    "v",
    "http://",
    "imyH",
    ".radar_tip",
    "kZNz",
    "by",
    ".reset_tip_content",
    ".panel_error_code_text",
    "passtime",
    "pow_wait_once",
    "seyv",
    "QZuN",
    "/ajax.php",
    "server_forbidden",
    "FyFJ",
    "shift",
    "bSpG",
    "api.geetest.com",
    "multi_line",
    "vip_order",
    "next_ready",
    "qgBS",
    "ct",
    "em",
    "cfCL",
    "fa",
    "sByl",
    "tt",
    "UxWu",
    "light",
    ".sector",
    "js_unload",
    ".panel",
    "error_content",
    "next_width",
    "Icve",
    "100%",
    ".panel_next",
    ".fullpage_click",
    "nextDebugConfig",
    "show",
    "onError",
    ".logo",
    "xADj",
    ".panel_success_title",
    "homepage",
    "AFXw",
    "getValidate",
    "ie",
    ".fullpage_click_box",
    "slide3",
    "wGln",
    ".success_logo",
    "DZBx",
    "eSdi",
    ".panel_loading_content",
    "copyright",
    "goto_homepage",
    "cancel",
    "onBack",
    "goto_cancel",
    "area",
    "Jfna",
    ".panel_box",
    "bg_color",
    "text/css",
    "Gekk",
    ".panel_footer",
    ".goto_confirm",
    "maze",
    "zoomEle",
    "KpWx",
    ".success_radar_tip",
    "oldQ",
    "shake",
    "logo",
    "onReady",
    "appendTo",
    "voice",
    ".goto_cancel",
    "beeline",
    "yfmn",
    "uoZB",
    ".goto_content_tip",
    "leave",
    "JJtT",
    ".panel_ghost",
    "Ha_A",
    "rotate(",
    ".goto",
    "goto_confirm",
    "enter",
    "Bapr",
    "hideClose",
    "autoReset",
    "FTSw",
    "onFail",
    "fallback",
    "error_title",
    "keyCode",
    ".dot",
    "onChangeCaptcha",
    "hideSuccess",
    "tBFz",
    "pencil",
    "_blank",
    "reversal_success",
    "reversal",
    "hideRefresh",
    "loading_content",
    "deg)",
    ".holder",
    "skin_path",
    "success_title",
    "embed",
    ".panel_error_content",
    "hide",
    "js_not_exist",
    "CFtj",
    "onClose",
    "apkk",
    ".panel_footer_copyright",
    "destroy",
    ".goto_ghost",
    "atan",
    "onSuccess",
    "aXAD",
    ".fullpage_click_wrap",
    "showBack",
    "LJlK",
    "",
    "refresh_page",
    "url_reset",
    "",
    "Rwtk",
    "",
    "api_appendTo",
    ".ghost_success",
    "YJJh",
    "",
    "geetest_challenge",
    ".fullpage_pointer",
    "",
    "confirm",
    "",
    "",
    "EKDS",
    "ZeFx",
    "theme_version",
    "Xavc",
    ".panel_success",
    "",
    "VPuR",
    "UQZc",
    "",
    "",
    "margin-top",
    "",
    "",
    ".panel_error",
    "margin-right",
    "no_logo",
    "api_bindForm",
    "",
    "WbpQ",
    ".form",
    "",
    "",
    "margin-left",
    "mfli",
    "fGpZzVnYeGgcwQ",
    "",
    "nOJJ",
    "",
    "_https",
    "landscape",
    "Pyca",
    "",
    "geetest_validate",
    "",
    ".panel_loading",
    "portrait",
    "Wtkr",
    "api_bindButton",
    "lwRX",
    "panelshowclick",
    "",
    "TfGU",
    "",
    "",
    ".css",
    "",
    ".fullpage_ghost",
    "",
    ".success_btn",
    ".wait",
    "",
    "",
    "EooL",
    ".challenge",
    "orientation",
    "",
    "STxN",
    "",
    "reload",
    "",
    "ie6panelshowclick",
    "",
    ".validate",
    "MLFc",
    "Qmxn",
    "",
    "panelshowslide",
    "",
    "OMsu",
    "rsBK",
    "panelshowbeeline",
    "",
    ".seccode",
    "/static/",
    "",
    "",
    "",
    "/style",
    "",
    "geetest_seccode",
    "success_animate",
    "",
    "font-family",
    ""
]


with open("/Users/PENGHanyuan/Documents/Programs/Herchat/Herchat/src/js/hermes.js", "r") as file:
    full = file.read()
new = full
for i, t in enumerate(content):
    # print('"{}"'.format(t))
    # print("kyWQ({})".format(i+1))
    x = "lMTR({})".format(i+1)
    y = "kyWQ({})".format(i+1)
    z = "MocY({})".format(i+1)
    z1 = "NVdx({})".format(i+1)
    z2 = "GWfq({})".format(i+1)
    z3 = "HQkM({})".format(i+1)
    z4 = "scdQ({})".format(i+1)
    z5 = "tOCd({})".format(i+1)
    z6 = "gQEp({})".format(i+1)
    z7 = "hHgW({})".format(i+1)
    z8 = "UjTX({})".format(i+1)
    z9 = "VDN_({})".format(i+1)



    m = '"{}"'.format(t)
    new = new.replace(x, m)
    new = new.replace(y, m)
    new = new.replace(z, m)
    new = new.replace(z1, m)
    new = new.replace(z2, m)
    new = new.replace(z3, m)
    new = new.replace(z4, m)
    new = new.replace(z5, m)
    new = new.replace(z6, m)
    new = new.replace(z7, m)
    new = new.replace(z8, m)
    new = new.replace(z9, m)





# print(new)
with open("/Users/PENGHanyuan/Documents/Programs/Herchat/Herchat/src/js/hermes_3.js", "w") as file:
    file.write(new)